set(probe_sources)
if(CONFIG_MAC_TRANSITION_PROBE)
    list(APPEND probe_sources "mac_transition_probe.c")
endif()
idf_component_register(SRCS ${probe_sources}
    PRIV_REQUIRES esp_wifi esp_timer esp_driver_gptimer esp_driver_mcpwm WHOLE_ARCHIVE)
if(CONFIG_MAC_TRANSITION_PROBE)
    if(CONFIG_MAC_TRANSITION_MCPWM)
        idf_component_get_property(timer_library esp_driver_mcpwm COMPONENT_LIB)
        target_sources(${timer_library} PRIVATE "${CMAKE_CURRENT_LIST_DIR}/mac_mcpwm_sample.c")
    else()
    idf_component_get_property(timer_library esp_driver_gptimer COMPONENT_LIB)
    target_sources(${timer_library} PRIVATE "${CMAKE_CURRENT_LIST_DIR}/mac_timer_sample.c")
    endif()
endif()
